
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author intel
 */
public class FormBiodata extends javax.swing.JFrame {

    /**
     * Creates new form FormBiodata
     */
    public FormBiodata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nis = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        perempuan = new javax.swing.JRadioButton();
        laki = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        refresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 370, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 30, 250, 30);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 70);
        getContentPane().add(nis);
        nis.setBounds(20, 130, 130, 30);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("ISIAN DATA SISWA"));
        jPanel2.setLayout(null);

        buttonGroup1.add(perempuan);
        perempuan.setText("Perempuan");
        jPanel2.add(perempuan);
        perempuan.setBounds(110, 160, 100, 23);

        buttonGroup1.add(laki);
        laki.setText("Laki-Laki");
        jPanel2.add(laki);
        laki.setBounds(10, 160, 90, 23);

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 320, 190, 100);

        jLabel15.setText("Alamat");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 290, 90, 30);
        jPanel2.add(email);
        email.setBounds(10, 260, 130, 30);

        jLabel14.setText("Email");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 240, 60, 30);
        jPanel2.add(kelas);
        kelas.setBounds(10, 210, 130, 30);

        jLabel10.setText("Kelas");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 180, 80, 30);

        jLabel9.setText("Jenis Kelamin");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 120, 110, 40);
        jPanel2.add(nama);
        nama.setBounds(10, 100, 130, 30);

        jLabel5.setText("Nama");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 80, 50, 20);

        jLabel7.setText("NIS");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 24, 40, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 80, 220, 430);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(610, 90, 80, 40);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(427, 90, 70, 40);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(250, 90, 80, 40);

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del);
        del.setBounds(340, 90, 80, 40);

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(240, 80, 470, 60);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "JenisKelamin", "Email", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(240, 170, 470, 340);

        setBounds(0, 0, 720, 561);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        if("".equals(nis.getText()) || "".equals(alamat.getText()) || "".equals(kelas.getText())|| "".equals(nama.getText())|| "".equals(email.getText()))
        {
            JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }
        else{
            String JK="";
            if(laki.isSelected())
            {
                JK = "L";
            }
            else
            {
                JK = "P";
            }
            String SQL = "INSERT INTO t_siswa(NIS,Nama Siswa,Jenis Kelamin,Kelas,Email,Alamat) " 
                    + "VALUES('"+nis.getText()+"','"+nama.getText()+"','"+JK+"',"
                            +"'"+kelas.getText()+"','"+email.getText()+"','"+alamat.getText()+"')";
               int status = KoneksiDB.execute(SQL);
               if (status == 1)
               {
                   JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                   selectData();
               }
               else{
                   JOptionPane.showMessageDialog(this,"Data Gagal Ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
               }}
    }//GEN-LAST:event_saveActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
        if (baris != -1)
        {
            String NIS = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if(status == 1)
            {
                JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this,"Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
           JOptionPane.showMessageDialog(this,"Pilih baris terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_delActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        nis.setText("");
        nama.setText("");
        kelas.setText("");
        buttonGroup1.clearSelection();
        email.setText("");
        alamat.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_refreshActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
         if("".equals(nis.getText()) || "".equals(alamat.getText()) || "".equals(kelas.getText())|| "".equals(nama.getText())|| "".equals(email.getText()))
        {
            JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }
        else{
            String JK="";
            if(laki.isSelected())
            {
                JK = "L";
            }
            else
            {
                JK = "P";
            }
            String SQL = "UPDATE t_siswa SET" 
                    + "WHERE NamaSiswa='"+nama.getText()+"',"+ "WHERE JenisKelamin='"+JK+"',"
                    + "WHERE Kelas='"+kelas.getText()+"',"+ "WHERE Email='"+email.getText()+"'"
                    + "WHERE Alamat='"+alamat.getText()+"'"+ "WHERE NIS='"+nis.getText()+"'";
               int status = KoneksiDB.execute(SQL);
               if (status == 0)
               {
                   JOptionPane.showMessageDialog(this,"Data Berhasil Diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                   selectData();
               }
               else{
                   JOptionPane.showMessageDialog(this,"Data Gagal Diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
               }}
    }//GEN-LAST:event_editActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        
        int baris = tabel.getSelectedRow();
        if(baris != 1)
        {
            nis.setText(tabel.getValueAt(baris, 0).toString());
            nama.setText(tabel.getValueAt(baris, 1).toString());
            if("Laki-Laki".equals(tabel.getValueAt(baris, 2).toString()))
            {
                laki.setSelected(true);
            }else{
                perempuan.setSelected(true);
            }
            kelas.setText(tabel.getValueAt(baris, 3).toString());
            email.setText(tabel.getValueAt(baris, 4).toString());
            alamat.setText(tabel.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void selectData() {
       String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM t_siswa";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next())
           {
               String NIS = rs.getString(1);
               String NamaSiswa = rs.getString(2);
               String JenisKelamin = "";
               if("L".equals(rs.getString(3)))
               {
                   JenisKelamin = "Laki-Laki";
               }
               else{
                   JenisKelamin = "Perempuan";
               }
               String Kelas = rs.getString(4);
               String Email = rs.getString(5);
               String Alamat = rs.getString(6);
               String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
                       dtm.addRow(data);
           }
       } catch(SQLException ex)
       {
           //Logger.getLogger(FormBiodata.class.getName()).Log(Level.SEVERE, null, ex);
       }
       tabel.setModel(dtm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBiodata().setVisible(true);
            }
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kelas;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    
}
